version: '3.8'

services:
  redis:
    container_name: redis-stack
    image: redis/redis-stack-server:latest
    ports:
      - "1234:6379"
    environment:
      REDIS_ARGS: "--requirepass 2048"
    networks:
      - my-network

  golang-websocket:
    build:
      context: .
      dockerfile: /home/gehnmart/Kursova/go-chat-app/Dockerfile
    ports:
      - "8081:8081"
    command: ./gochatapp --server=websocket
    networks:
      - my-network
    depends_on:
      - redis
      - golang-http

  golang-http:
    build:
      context: .
      dockerfile: /home/gehnmart/Kursova/go-chat-app/Dockerfile
    ports:
      - "8080:8080"
    command: ./gochatapp --server=http
    networks:
      - my-network
    depends_on:
      - redis
  
  node:
    image: node:20
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    working_dir: /app
    command: npm start
    networks:
      - my-network
    depends_on:
      - golang-websocket
networks:
  my-network:
    driver: bridge
