version: '3.2'

services:
  redis:
    container_name: redis-stack
    image: redis/redis-stack-server:latest
    ports:
      - "2048:6379"
    environment:
      REDIS_ARGS: "--requirepass 2048"
    networks:
      - my-network

  golang-websocket:
    container_name: golang-websocket
    ports:
      - "8081:8081"
    build:
      context: .
      dockerfile: Dockerfile
    command: ./gochatapp --server=websocket
    networks:
      - my-network
    depends_on:
      - redis

  golang-http:
    container_name: golang-http
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    command: ./gochatapp --server=http
    networks:
      - my-network
    depends_on:
      - redis
  
  node:
    container_name: node
    image: node:18
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    networks:
      - my-network
    depends_on:
      - golang-websocket

networks:
  my-network:
    driver: bridge

